### ISSUE TITLE
createindex.job.yaml url_virus should be corrected

### ISSUE THREAD

**Issue by zhangzlab** [yyoshiaki/VIRTUS#12]
I noticed the address for the virus sequence has been changed to viruses.fasta, which is not correct in createindex.job.yaml url_virus config. Can you change the yaml config?

**Comment by Aiuthss** [comment]
#15 
Thank you for your important suggestion. 
The source of virus fasta file was changed from data/viruses_763.fasta to data/viruses.fasta.

**Comment by patrick-douglas** [comment]
Hi
How can I use a custom virus database which is located locally on my computer?

Best 
Patrick
