### ISSUE TITLE
STAR --genomeSAindexNbases setting

### ISSUE THREAD

**Issue by zhangzlab** [yyoshiaki/VIRTUS#18]
Dear,

I encountered the Segmentation fault (core dumped) at the STAR alignReads to the virus genome step. Then  I checked the genomeSAindexNbases parameter in the virus index creation step and found the following warning.

'WARNING: --genomeSAindexNbases 14 is too large for the genome size=199753728, which may cause seg-fault at the mapping step. Re-run genome generation with recommended --genomeSAindexNbases 12'

Two questions:
1. The recommended genomeSAindexNbases of STAR is min(14, log2(GenomeLength)/2 - 1). I noticed the GenomeLength of all virus genomes is just 198153, why 199753728 here.
2. Should I change the genomeSAindexNbases in the virus index creation step?

**Comment by zhangzlab** [comment]
I recreated the index with genomeSAindexNbases = 12, and now it's ok.

**Comment by yyoshiaki** [comment]
Thank you for pointing it out, and sorry for my late reply.  Actually, in `createindex.cwl`, we used the default `--genomeSAindexNbases`. In the next release, we consider specifying smaller `--genomeSAindexNbases`.

**Comment by yyoshiaki** [comment]
Fixed in #22 . Thank you!
