### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by mabouelk** [yyoshiaki/VIRTUS#2]
Hi 
I am so exicted to use your tool and cite it in my paper. Please can you help me?
mabouelk@js-17-152:~/VIRTUS/test$ bash test.sh
+ [[ ! -e ./ERR3240275/ERR3240275_1.fastq.gz ]]
+ mkdir -p ERR3240275
+ cd ERR3240275
+ echo null
+ ls
+ grep -v -E ERR3240275_1.fastq.gz
+ grep -v -E ERR3240275_2.fastq.gz
+ xargs rm -r
+ cd ..
+ [[ ! -e ./SRR8315715/SRR8315715_1.fastq.gz ]]
+ mkdir -p SRR8315715
+ cd SRR8315715
+ echo null
+ ls
+ grep -v -E SRR8315715_1.fastq.gz
+ grep -v -E SRR8315715_2.fastq.gz
+ xargs rm -r
+ cd ..
+ echo null
+ ls
+ grep -v -E test.sh
+ grep -v -E ERR3240275
+ xargs rm -r
+ grep -v -E SRR8315715
+ ../workflow/createindex.cwl ../workflow/createindex.job.yaml
/usr/bin/env: ?cwltool?: No such file or directory

**Comment by mabouelk** [comment]
ok, I managed to reinstall cwltool  using miniconda but I got this error:
ERROR I'm sorry, I couldn't load this CWL file, try again with --debug for more information.
The error was: cwltool requires Node.js engine to evaluate and validate Javascript expressions, but couldn't find it.  Tried nodejs, node, docker run node:slim

**Comment by yyoshiaki** [comment]
Hi, @mabouelk, Thank you for trying our tool!

You look failing the installation of cwl. Please refer to https://github.com/common-workflow-language/cwltool .

**Comment by mabouelk** [comment]
Thank you so much for your quick response, 
I did but I got this 
ERROR Workflow or tool uses unsupported feature:
Docker is required to run this tool: Command '['docker', 'images', '--no-trunc', '--all']' returned non-zero exit status 1.

**Comment by yyoshiaki** [comment]
Install Docker!

**Comment by mabouelk** [comment]
I am using my institution virtual machine which already has docker.  I tried to run it on my macbook pro but It failed (i think because the memory is not enough!) :

[job star_index] Max memory used: 14558MiB
WARNING [job star_index] completed permanentFail
WARNING [step star_index] completed permanentFail
INFO [workflow rnaseq_star_index_human] completed permanentFail
WARNING [step rnaseq_star_index_human] completed permanentFail
INFO [workflow ] completed permanentFail
{
    "downloaded_virus": null,
    "starIndex_virus": null,
    "starIndex_human": {
        "location": "file:///Users/moh/VIRTUS/test/STAR_index_human",
        "basename": "STAR_index_human",
        "class": "Directory",
        "listing": [],
        "path": "/Users/moh/VIRTUS/test/STAR_index_human"
    },
    "downloaded_genomefasta_human": {
        "location": "file:///Users/moh/VIRTUS/test/GRCh38.p13.genome.fa.gz",
        "basename": "GRCh38.p13.genome.fa.gz",
        "class": "File",
        "checksum": "sha1$2b7cdbbf55b0c507ad6f56de3afb2fe9ff8a8da5",
        "size": 889409368,
        "path": "/Users/moh/VIRTUS/test/GRCh38.p13.genome.fa.gz"
    },
    "salmon_index_human": null,
    "downloaded": {
        "location": "file:///Users/moh/VIRTUS/test/gencode.v33.transcripts.fa.gz",
        "basename": "gencode.v33.transcripts.fa.gz",
        "class": "File",
        "checksum": "sha1$a1ea3698bb266dcc05f12524037203f9bdf4da5b",
        "size": 72861419,
        "path": "/Users/moh/VIRTUS/test/gencode.v33.transcripts.fa.gz"
    }
}
WARNING Final process status is permanentFail

**Comment by mabouelk** [comment]
back to the cluster, I fixed the installation but it stop and I see that in the log file 

ocker: Error response from daemon: invalid mount config for type "bind": \
bind source path does not exist: /tmp/_igilf53.
See 'docker run --help'.

**Comment by yyoshiaki** [comment]
\>32Gb RAM is required, so the cluster is better.

about the docker bug, I cannot solve it quickly. Maybe, it is relating to the docker installation and configuration on your cluster. Please make sure whether docker works well besides VIRTUS, the docker version, and related issues on Google.

If I come up with an idea, I share it.

**Comment by yyoshiaki** [comment]
@mabouelk 
If it is difficult to install Docker on your cluster, udocker is another option. Good luck!
