### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by fjmuzengyiheng** [yyoshiaki/VIRTUS#20]
Hi, I get this error when I try to create indices.

Here is my command:

     createindex.cwl https://raw.githubusercontent.com/yyoshiaki/VIRTUS/master/workflow/createindex.job.yaml

An error occurred below:

INFO /home/zengyiheng/miniconda3/bin/cwltool 3.0.20200807132242
INFO Resolved '/home/zengyiheng/biosoft/virtus/VIRTUS/bin/createindex.cwl' to 'file:///home/zengyiheng/biosoft/virtus/VIRTUS/bin/createindex.cwl'
ERROR Tool definition failed validation:
Error fetching https://raw.githubusercontent.com/yyoshiaki/VIRTUS/master/workflow/createindex.job.yaml: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /yyoshiaki/VIRTUS/master/workflow/createindex.job.yaml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3daa117bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))

I can't figure it out. Could someone help me?
Thanks a lot.
Yi-Heng Zeng

**Comment by yyoshiaki** [comment]
Thank you for trying! It looks network error. How about executing it without https like below,

```
createindex.cwl /path/to/createindex.job.yaml
```

You can find 'createindex.job.yaml` in `VIRTUS/workflow` or https://github.com/yyoshiaki/VIRTUS/blob/master/workflow/createindex.job.yaml .

Yoshi
