### ISSUE TITLE
index building 

### ISSUE THREAD

**Issue by tickteng** [yyoshiaki/VIRTUS#21]
Hi,

I want to try this pipeline. I use udocker since I do not have the root privilege.
However, when I tried to build the index,  I run the following command
createindex.cwl https://raw.githubusercontent.com/yyoshiaki/VIRTUS/master/workflow/createindex.job.yaml

I tweaked the createindex.cwl file by adding the --user-space-docker-cmd=udocker on the first line. However, when I run the command, I get no output, nor error, nor any progress notifications.
Am I running this correctly?
Any help would be appreciated.

**Comment by tickteng** [comment]
installed nodejs and it works now.

**Comment by yyoshiaki** [comment]
Keep it up!

**Comment by tickteng** [comment]
Hi again,
The index buildin was running smooth for a while.
It created the index for human, but when creating the index for virus, the following error appears.

INFO [job wget_virus] /tmp/me9s33oy$ udocker \
    --quiet \
    run \
    --volume=/tmp/me9s33oy:/XFkviA \
    --volume=/tmp/2q5gdjp4:/tmp \
    --workdir=/XFkviA \
    --rm \
    --env=TMPDIR=/tmp \
    --env=HOME=/XFkviA \
    alpine:3.9 \
    wget \
    --output-document=viruses.fasta \
    https://raw.githubusercontent.com/yyoshiaki/VIRTUS/master/data/viruses.fasta 2> /tmp/me9s33oy/wget-stderr.log
INFO [job wget_virus] Max memory used: 13MiB
ERROR [job wget_virus] Job error:
("Error collecting output for parameter 'downloaded':\n../VIRTUS/tool/wget/wget.cwl:31:7: Did not find output file with glob pattern: '['viruses.fasta']'", {})
WARNING [job wget_virus] completed permanentFail
ERROR [step wget_virus] Output is missing expected field file:///home/virtus/VIRTUS/bin/createindex.cwl#createindex/wget_virus/downloaded
ERROR [step wget_virus] Output is missing expected field file:///home/virtus/VIRTUS/bin/createindex.cwl#createindex/wget_virus/stderr
WARNING [step wget_virus] completed permanentFail
INFO [workflow ] completed permanentFail
{
    "downloaded_virus": null,
    "starIndex_virus": null,
    "starIndex_human": null,
    "downloaded_genomefasta_human": null,
    "salmon_index_human": null,
    "downloaded": null
}
WARNING Final process status is permanentFail

**Comment by tickteng** [comment]
update

now I got this following error

$ createindex.cwl --user-space-docker-cmd=udocker ./VIRTUS/bin/createindex.job.yaml 
INFO /home/miniconda3/envs/virtuspython3/bin/cwltool 3.0.20200807132242
INFO Resolved '/home/Documents/VIRTUS/bin/createindex.cwl' to 'file:///home/Documents/VIRTUS/bin/createindex.cwl'
VIRTUS/bin/createindex.cwl:39:5: object id `VIRTUS/bin/createindex.cwl#createindex/salmon_index_human` previously defined
VIRTUS/bin/createindex.cwl:39:5: object id `VIRTUS/bin/createindex.cwl#createindex/salmon_index_human` previously defined
VIRTUS/bin/createindex.cwl:144:9: object id `VIRTUS/bin/createindex.cwl#createindex/salmon_index_human/index` previously defined
VIRTUS/tool/salmon-cwl/salmon-index.cwl:8:5: object id `VIRTUS/tool/salmon-cwl/salmon-index.cwl#index` previously defined
usage: /home/patrick/Documents/VIRTUS/bin/createindex.cwl [-h] --url_virus
                                                          URL_VIRUS
                                                          --output_name_virus
                                                          OUTPUT_NAME_VIRUS
                                                          [--runThreadN RUNTHREADN]
                                                          --dir_name_STAR_virus
                                                          DIR_NAME_STAR_VIRUS
                                                          --url_genomefasta_human
                                                          URL_GENOMEFASTA_HUMAN
                                                          --output_name_genomefasta_human
                                                          OUTPUT_NAME_GENOMEFASTA_HUMAN
                                                          --dir_name_STAR_human
                                                          DIR_NAME_STAR_HUMAN
                                                          --salmon_index_human
                                                          SALMON_INDEX_HUMAN
                                                          --url_transcript_human
                                                          URL_TRANSCRIPT_HUMAN
                                                          --output_name_human_transcipt
                                                          OUTPUT_NAME_HUMAN_TRANSCIPT
                                                          [job_order]
/home/Documents/VIRTUS/bin/createindex.cwl: error: the following arguments are required: --url_virus, --output_name_virus, --dir_name_STAR_virus, --url_genomefasta_human, --output_name_genomefasta_human, --dir_name_STAR_human, --salmon_index_human, --url_transcript_human, --output_name_human_transcipt

**Comment by yyoshiaki** [comment]
I got the same error, but somehow, after adding `--debug` option, it successfully finished.

**Comment by yyoshiaki** [comment]
in development v1.2.1, we fixed it. Can you try to switch the branch to development1.2.1 and re-try it?
