### ISSUE TITLE
docker tag should be latest

### ISSUE THREAD

**Issue by qiyubio** [yyoshiaki/VIRTUS#25]
Hi, I was testing VIRTUS. There is a problem pulling `mk_summary_virus_count` image because there is no tag 1.1, only `latest`. I manually pulled the image with tag `latest`, and it works fine. 

Please change the docker tag or the code here:
https://github.com/yyoshiaki/VIRTUS/commit/01534809718c47101c11b81bb21c9c923cd9fe1f#diff-1ecee707f5238bc63f35c8c3574563a3ce9ddada5b833964c12bf73239efb16cR30

Thanks.

**Comment by yyoshiaki** [comment]
Hi @qiyubio,
thank you for pointing it out. I fixed the tag of `yyasumizu/mk_summary_virus_count` accordingly on docker hub.
https://hub.docker.com/repository/docker/yyasumizu/mk_summary_virus_count/tags?page=1&ordering=last_updated
