### ISSUE TITLE
ERROR Tool definition failed validation

### ISSUE THREAD

**Issue by nmc-ei** [yyoshiaki/VIRTUS#27]
Hi,
I try to create indices.
```
createindex.cwl https://raw.githubusercontent.com/yyoshiaki/VIRTUS/master/workflow/createindex.job.yaml
　　　　　　　　　　　　　　　　　　　　　　　　　　　OR
createindex.cwl workflow/createindex.job.yaml
　　　　　　　　　　　　　　　　　　　　　　　　　　　OR
cwltool --singularity workflow/createindex.cwl workflow/createindex.job.yaml
```

but these command return error.

```
INFO /home/hoge/anaconda3/envs/cwl_env/bin/cwltool 3.1.20210426140515
INFO Resolved '/share/home/hoge/VIRTUS/bin/createindex.cwl' to 'file:///yshare2/home/hoge/VIRTUS/bin/createindex.cwl'
../../../../home/hoge/VIRTUS/bin/createindex.cwl:39:5: object id `../../../../home/hoge/VIRTUS/bin/createindex.cwl#createindex/salmon_index_human` previously defined
../../../../home/hoge/VIRTUS/bin/createindex.cwl:39:5: object id `../../../../home/hoge/VIRTUS/bin/createindex.cwl#createindex/salmon_index_human` previously defined
../../../../home/hoge/VIRTUS/bin/createindex.cwl:148:9: object id `../../../../home/hoge/VIRTUS/bin/createindex.cwl#createindex/salmon_index_human/index` previously defined
ERROR Tool definition failed validation:
../../../../home/hoge/VIRTUS/bin/createindex.cwl:10:1: union[str, int, bool, schema_salad.avro.schema.Schema, list, list, dict, list, None] object expected; got ruamel.yaml.scalarfloat.ScalarFloat
```

Thank you.

**Comment by yyoshiaki** [comment]
Hi, thank you for using our tool!

I tried `createindex.cwl https://raw.githubusercontent.com/yyoshiaki/VIRTUS/master/workflow/createindex.job.yaml` on several machines and environments including cwltool 3.1.20210426140515, but I failed to reproduce the error.
Did you edit the cwl files on your computer?

Yoshi

**Comment by nmc-ei** [comment]
Thank you for your reply.

No. I didn't edit the cwl files.

**Comment by yyoshiaki** [comment]
What are your Python and schema_salad version? If 3.9, this PR may solve the problem.
https://github.com/common-workflow-language/schema_salad/issues/385
https://github.com/common-workflow-language/schema_salad/pull/386

**Comment by nmc-ei** [comment]
I checked the version of schema_salad and found that it was not installed for some reason, so I reinstalled cwlref-runner.
Then the command "cwltool --singularity workflow/createindex.cwl workflow/createindex.job.yaml" was ran without error. However, some warnings are present.
```
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
WARNING: Building container as an unprivileged user. If you run this container as root
WARNING: it may be missing some functionality.
WARNING [job wget_transcipt] completed permanentFail
WARNING [step wget_transcipt] completed permanentFail
WARNING Final process status is permanentFail
```
Can I ignore these warnings?

**Comment by yyoshiaki** [comment]
> WARNING Final process status is permanentFail

It seems the process failed. Can you share the output files?

**Comment by nmc-ei** [comment]
Do you mean you need all the standard output?
[virtus_output.txt](https://github.com/yyoshiaki/VIRTUS/files/6520825/virtus_output.txt)

**Comment by yyoshiaki** [comment]
The process looks not to have been appropriately finished. I do not understand how Singularity works well. Can you switch it to docker? 

or, `/tmp/0uibbzdw/wget-stderr.log` may contain information about the solution.

**Comment by nmc-ei** [comment]
I can't switch it to doker.
And I can't found `/tmp/0uibbzdw/wget-stderr.log`.

**Comment by yyoshiaki** [comment]
I verified `--singularity` worked as well on our computer. Can you add `--debug` flag and execute createindex.cwl again?

**Comment by nmc-ei** [comment]
[virtus_output_debug.txt](https://github.com/yyoshiaki/VIRTUS/files/6521343/virtus_output_debug.txt)

**Comment by yyoshiaki** [comment]
put options before files like

`cwltool --debug --singularity workflow/createindex.cwl workflow/createindex.job.yaml`

**Comment by nmc-ei** [comment]
Sorry.
[virtus_output_debug2.txt](https://github.com/yyoshiaki/VIRTUS/files/6536624/virtus_output_debug2.txt)

**Comment by yyoshiaki** [comment]
Thank you. The download of `https://raw.githubusercontent.com/yyoshiaki/VIRTUS/master/data/viruses.fasta` looks succeeded whereas that of `ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_33/gencode.v33.transcripts.fa.gz` failed. Because both procedures use the same container, it may be due to a fire wall or something.
Can you do `wget ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_33/gencode.v33.transcripts.fa.gz` on your computer? Otherwise, I have completely no idea...

**Comment by nmc-ei** [comment]
I try `wget ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_33/gencode.v33.transcripts.fa.gz`.
But it failed due to errors in the server response.

I apologize for any inconvenience this may cause.
Thank you very much.

**Comment by yyoshiaki** [comment]
It's my pleasure, thank you for trying our tool and reporting an issue!
