### ISSUE TITLE
How to run wrapper with specific single virus

### ISSUE THREAD

**Issue by KevinMaroney** [yyoshiaki/VIRTUS#37]
Hi Yoshiaki! I'm sorry to keep bothering you.

The kind help you offered me a week ago was extremely useful, as I generated some beautiful data for a grant that will probably be its central focus and maybe even a paper. You suggested using VIRTUS1 for single viral genome counting/comparisons. I assume I am supposed to use "createindex_singlevirus.cwl" but was wondering if it has the same inputs as for createindex, as well as if the method for running the VIRTUS wrapper is the same and I just have to point to the new single virus index. Does it download annotated genomes for all viruses in parallel or do I have to choose mine as an input? I'm focusing on HPV18 which I was overjoyed to find in most of my cancer samples.

I apologize if this information is included in one of your README files. If you could even just point me in the right direction I would be very thankful. Thank you for developing this one-of-a-kind tool that I think everybody wanted to see but noone but you and the author of Virtect took on. I'm sure it was a massive undertaking.

**Comment by yyoshiaki** [comment]
Hi, that sounds great!

Regarding createindex_singlevirus.cwl, you must prepare "transcript sequences" of your interested virus and the genome sequence. 
For HPV18, you can download all required files in NCBI https://www.ncbi.nlm.nih.gov/nuccore/NC_001357.1 .
In more detail, please refer to the wiki https://github.com/yyoshiaki/VIRTUS/wiki/Tool-descriptions and the example job.
